### ISSUE TITLE
使用Xib 添加的UITableview 检查未释放

### ISSUE THREAD

**Issue by yinanwang1** [Tencent/MLeaksFinder#26]
添加断点，看到已经执行了MainViewController的dealloc方法。 但是提示UITableview没有被释放，这个UITableview是通过Xib添加的。

In case that UITableView should not be dealloced, override -willDealloc in UITableView by returning NO.
View-ViewController stack: (
    MainViewController,
    UIView,
    UIView,
    UITableView
)

**Comment by Zepo** [comment]
自定义一个 UITableView 的子类；
把上面的 UITableView 替换成自定义的类；
在 dealloc 里加断点看有没有进就知道是不是误报了。

**Comment by yinanwang1** [comment]
添加了一个UITableview的子类，执行没有进入子类的dealloc方法，还是报了In case that TestTableView should not be dealloced, override -willDealloc in TestTableView by returning NO.

**Comment by Zepo** [comment]
你得先把 MLeaksFinder 关掉，在 MLeaksFinder.h 里加上宏 #define MEMORY_LEAKS_FINDER_ENABLED 0
然后看有没有进入子类的 dealloc，没进的话就真的是泄漏了。

**Comment by yinanwang1** [comment]
定义了一个UITableViewCell的子类BuildingTableViewCell
- (void)dealloc
{
    _leftBarView = nil; // [self.contentView addSubview:_leftBarView]; 在cell的contentView添加一个UIView
}
已经编写了dealloc，在关掉MLeaksFinder的时候，会执行dealloc的方法。当打开MLeaksFinder后，不执行dealloc方法，错误的stack为
In case that UITableViewCellContentView should not be dealloced, override -willDealloc in UITableViewCellContentView by returning NO.
View-ViewController stack: (
    AddressSelectVewController,
    UIView,
    UITableView,
    AddressDecorationView,
    UIView,
    UITableView,
    UITableViewWrapperView,
    HXSBuildingTableViewCell,
    UITableViewCellContentView
) 

有没有可能对UITableViewCellContentView的误报？

**Comment by Zepo** [comment]
一般不会，好好检查一下你的代码，哪里用到 cell.contentView 了，注释掉试试

**Comment by JavenZ** [comment]
我也遇到了，用的系统样式的cell，在返回cell的方法如下：
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:kCellId forIndexPath:indexPath];
    VankeShopModel *shop = self.results[indexPath.row];
    cell.textLabel.text = [NSString stringWithFormat:@"%@【%@】", shop.name, shop.code];
    return cell;
}

实在找不到哪里有内存泄露，希望对你完善框架有帮助。
PS:框架非常赞 : )
