### ISSUE TITLE
Why ViewController presentation always leak?

### ISSUE THREAD

**Issue by weiminghuaa** [Tencent/MLeaksFinder#27]
ViewController A present ViewController B and B implementation this method, B's root view always leak
`- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
    [self cancelAction:nil];
    [self dismissViewControllerAnimated:animated completion:nil];
}`

**Comment by Zepo** [comment]
This is a known issue. A UITouch will retain the view under it until the next touch occurring.

**Comment by Zepo** [comment]
fix
