### ISSUE TITLE
使用UIAlerViewController的actionSheet样式的时候提示内存泄露

### ISSUE THREAD

**Issue by JavenZ** [Tencent/MLeaksFinder#29]
改成alert样式，其它代码没有任何变动，就没有泄露了。
我用的OC

**Comment by sauchye** [comment]
https://github.com/Zepo/MLeaksFinder/issues/12 .
这里有说明

**Comment by Zepo** [comment]
duplicate https://github.com/Tencent/MLeaksFinder/issues/12
