### ISSUE TITLE
Retain Cycle: Fail to find a retain cycle

### ISSUE THREAD

**Issue by fengyun911** [Tencent/MLeaksFinder#46]
What is the meaning of this kind of circumstance is a circular reference, or no circular references

**Comment by Zepo** [comment]
You can refer to https://github.com/Zepo/MLeaksFinder/blob/master/README-CN.md

**Comment by mafeng-Bryant** [comment]
I use MLeaksFinder to check cycle,but tips fail to find a retain cycle, why?

**Comment by wqforever** [comment]
https://github.com/Zepo/MLeaksFinder/blob/master/README-CN.md
这篇文章404了
