### ISSUE TITLE
手动添加 MLeaksFinder 不生效

### ISSUE THREAD

**Issue by sdlbp** [Tencent/MLeaksFinder#58]
手动添加整个工程之后，在 UIViewController+MemoryLeak.m 的 + (void)load 方法里加断点，断点没有进入。

**Comment by sdlbp** [comment]
问题已经解决了。
原因是：#define _INTERNAL_MLF_ENABLED DEBUG 这种方式控制编译，如果个别项目在 build settiong -> preprocessor macros 中设置了预编译宏，有可能出错。

**Comment by zdrjson** [comment]
I have the same issue as you, how to fix the problem?

**Comment by sdlbp** [comment]
@zdrjson  我是因为把 build setting -> preprocessor macros 里面的 DEBUG 删除了
