### ISSUE TITLE
swizzl方法里缺少响应验证

### ISSUE THREAD

**Issue by BOOLWORK** [Tencent/MLeaksFinder#59]
swizzl方法里缺少响应验证,导致不识别方法的崩溃,是不是要加上[self respondsToSelector:@selector...的验证 @Zepo

**Comment by BOOLWORK** [comment]
![2017-06-13 10 59 00](https://user-images.githubusercontent.com/18599527/27064104-3386d816-5028-11e7-9bcf-e539992ebf58.png)

**Comment by Zepo** [comment]
这个是业务逻辑层的问题，应该由业务逻辑层自己判断。这里 swizzle 只是更改了方法的实现，并没有改变方法会不会被调用。
