### ISSUE TITLE
使用上的问题

### ISSUE THREAD

**Issue by bytegh** [Tencent/MLeaksFinder#83]
hi 很感谢您分享这么棒的工具，但是我使用的时候碰到了问题，
我是用了pod以及手动添加的方式，而且设置断点load方法是有被调用的，
但是当我测试的时候，我push进去了很多个vc，然后pop出来，但是都没有发现willDealloc被调用。请问是什么问题呢？

**Comment by Zepo** [comment]
1. 有没有修改系统的 popViewControllerAnimated: 或者 viewDidDisappear: 方法，或者忘了调 [super viewDidDisappear:xxx]
2. 可以在 UINavigationController+MemoryLeak.m 的 swizzled_popViewControllerAnimated: 以及 UIViewController+MemoryLeak.m 的 swizzled_viewDidDisappear: 里加断点调试下看看

如果还不行可以提供个 demo。

**Comment by bytegh** [comment]
恩 好的 多谢 我去试试!
